from pipeline.face_matching.mtcnn.exceptions.invalid_image import InvalidImage
